# Generated by Django 3.0.7 on 2020-07-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_post_published_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
